# framework.properties -
#

# ----------------------------------------------------------------
# Server connection information
# ----------------------------------------------------------------

framework.server.name = localhost
framework.server.hostname = localhost
framework.server.port = 4440
framework.server.url = http://localhost:4440

# ----------------------------------------------------------------
# Installation locations
# ----------------------------------------------------------------

rdeck.base=C:/projetos/rundeck

framework.projects.dir=C:/projetos/rundeck/projects
framework.etc.dir=C:/projetos/rundeck/etc
framework.var.dir=C:/projetos/rundeck/var
framework.tmp.dir=C:/projetos/rundeck/var/tmp
framework.logs.dir=C:/projetos/rundeck/var/logs
framework.libext.dir=C:/projetos/rundeck/libext

# ----------------------------------------------------------------
# SSH defaults for node executor and file copier
# ----------------------------------------------------------------

framework.ssh.keypath = C:/Users/55319/.ssh/id_rsa
framework.ssh.user = 55319

# ssh connection timeout after a specified number of milliseconds.
# "0" value means wait forever.
framework.ssh.timeout = 0

# ----------------------------------------------------------------
# Auto generated server UUID: e4781303-db15-4038-a190-51e5a55e18a1
# ----------------------------------------------------------------
rundeck.server.uuid = e4781303-db15-4038-a190-51e5a55e18a1

# ----------------------------------------------------------------
# System-wide global variables.
# ----------------------------------------------------------------

# Expands to ${globals.var1}
#framework.globals.var1 = value1

# Expands to ${globals.var2}
#framework.globals.var2 = value2

