#rdeck setup preferences
#Tue May 05 11:01:22 BRT 2026
awt.toolkit=sun.awt.windows.WToolkit
framework.logs.dir=C\:/projetos/rundeck/var/logs
java.specification.version=11
framework.rdeck.base.win=C\:\\projetos\\rundeck
sun.cpu.isalist=amd64
sun.jnu.encoding=Cp1252
framework.application.libpath=
sun.arch.data.model=64
framework.project.default.name=demo
java.vendor.url=https\://openjdk.java.net/
framework.email.mailhost=localhost
framework.nodes.file.name=resources.xml
sun.boot.library.path=C\:\\Program Files\\Java\\jdk-11\\bin
sun.java.command=.\\\\rundeck-5.8.0-20241205.war
jdk.debug=release
sun.stderr.encoding=cp850
java.specification.vendor=Oracle Corporation
java.version.date=2024-07-16
logging.config=C\:\\projetos\\rundeck/server/config/log4j2.properties
java.home=C\:\\Program Files\\Java\\jdk-11
file.separator=\\
java.vm.compressedOopsMode=32-bit
sun.stdout.encoding=cp850
line.separator=\r\n
java.specification.name=Java Platform API Specification
java.vm.specification.vendor=Oracle Corporation
jndi.roleMemberRDN=uniqueMember
framework.email.failonerror=true
framework.var.dir=C\:/projetos/rundeck/var
jndi.connectionPassword=secret
framework.server.url=http\://localhost\:4440
framework.email.mailport=25
framework.rdeck.base=C\:/projetos/rundeck
user.script=
java.protocol.handler.pkgs=org.springframework.boot.loader
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
java.runtime.version=11.0.24+7-LTS-271
user.name=55319
framework.server.name=localhost
framework.project.default.create=false
file.encoding=Cp1252
rdeck.base=C\:/projetos/rundeck
server.http.port=4440
java.vendor.version=18.9
micronaut.classloader.logging=true
java.io.tmpdir=C\:\\Users\\55319\\AppData\\Local\\Temp\\
java.version=11.0.24
framework.ssh.user=55319
PID=6180
java.vm.specification.name=Java Virtual Machine Specification
user.java_home=C\:/Program Files/Java/jdk-11
java.awt.printerjob=sun.awt.windows.WPrinterJob
sun.os.patch.level=
CONSOLE_LOG_CHARSET=UTF-8
framework.server.port=4440
java.library.path=C\:\\Program Files\\Java\\jdk-11\\bin;C\:\\Windows\\Sun\\Java\\bin;C\:\\Windows\\system32;C\:\\Windows;C\:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C\:\\Users\\55319\\AppData\\Local\\Programs\\Python\\Python313\\Scripts\\;C\:\\Users\\55319\\AppData\\Local\\Programs\\Python\\Python313\\;C\:\\ffmpeg\\bin;C\:\\Windows\\system32;C\:\\Windows;C\:\\Windows\\System32\\Wbem;C\:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C\:\\Windows\\System32\\OpenSSH\\;C\:\\Users\\55319\\Desktop\\poppler\\bin;C\:\\Program Files\\gs\\gs10.00.0\\bin;C\:\\ProgramData\\chocolatey\\bin;C\:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C\:\\Program Files\\Git\\cmd;C\:\\Users\\55319\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\;C\:\\Users\\55319\\AppData\\Local\\Programs\\Python\\Python310\\;C\:\\Users\\55319\\AppData\\Local\\Microsoft\\WindowsApps;C\:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.1.3\\bin;C\:\\Users\\55319\\Desktop\\poppler\\poppler\\bin;C\:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick;C\:\\Users\\55319\\AppData\\Local;C\:\\Program Files\\Docker\\Docker\\resources\\bin;C\:\\PROGRA~1\\Java\\JDK18~1.0_2\\bin;C\:\\Users\\55319\\Desktop\\hadoop\\hadoop-2.7.3\\bin;C\:\\Users\\55319\\Desktop\\hadoop\\hadoop-2.7.3\\bin;C\:\\Users\\55319\\Desktop\\Spark\\spark-3.1.2-bin-hadoop2.7\\bin;C\:\\Program Files\\MySQL\\MySQL Server 9.0\\bin;C\:\\Program Files\\nodejs\\;C\:\\Program Files\\dotnet\\;C\:\\Users\\55319\\AppData\\Local\\Microsoft\\WindowsApps;C\:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.1.3\\bin;;C\:\\Users\\55319\\Desktop\\poppler\\poppler\\bin;C\:\\Program Files\\Tesseract-OCR;C\:\\Program Files\\ImageMagick-7.1.1-Q16-HDRI\\magick;C\:\\Users\\55319\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C\:\\Users\\55319\\AppData\\Roaming\\npm;.
java.vendor=Oracle Corporation
framework.src.dir=C\:/projetos/rundeck/src
java.specification.maintenance.version=2
rdeck.base.win=C\:\\projetos\\rundeck
sun.io.unicode.encoding=UnicodeLittle
framework.server.hostname=localhost
framework.metadata.rootDir=C\:/projetos/rundeck/projects
sun.desktop=windows
log4j.configurationFile=file\:///C\:/projetos/rundeck/server/config/log4j2.properties
jndi.roleBase=cn\=roles,dc\=yourcompany,dc\=com
java.class.path=.\\\\rundeck-5.8.0-20241205.war
grails.env.initializing=false
framework.log.format=[yyyy-MM-dd hh\:mm\:ss-Z]
java.vm.vendor=Oracle Corporation
framework.email.password=
framework.email.user=
framework.email.from=root@localdomain
user.variant=
user.timezone=America/Sao_Paulo
org.jboss.logging.provider=slf4j
java.home.win=C\:\\Program Files\\Java\\jdk-11
os.name=Windows 10
java.vm.specification.version=11
sun.java.launcher=SUN_STANDARD
user.country=BR
rd.rtenv=production
jndi.userNameRDN=cn
sun.cpu.endian=little
user.home=C\:/Users/55319
user.language=pt
framework.ssh.keypath=C\:/Users/55319/.ssh/id_rsa
rundeck.config.location=C\:\\projetos\\rundeck\\server\\config\\rundeck-config.properties
rundeck.server.dataDir=C\:/projetos/rundeck/server
framework.server.password=admin
framework.email.replyto=do-not-reply
jndi.userBase=dc\=yourcompany,dc\=com
framework.crypto.jarSigning.aliasName=
org.grails.MAIN_CLASS_NAME=grails.plugins.mail.Application
framework.project.organization=demo
framework.etc.dir.win=C\:\\projetos\\rundeck\\etc
FILE_LOG_CHARSET=UTF-8
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.headless=true
jndi.connectionName=cn\=Manager,dc\=yourcompany,dc\=com
rundeck.server.configDir=C\:/projetos/rundeck/server/config
framework.email.ssl=false
framework.application.properties=
path.separator=;
jndi.roleNameRDN=cn
framework.server.username=admin
os.version=10.0
java.runtime.name=Java(TM) SE Runtime Environment
framework.rdeck.version=1.1
framework.projects.dir.win=C\:\\projetos\\rundeck\\projects
spring.beaninfo.ignore=true
user.java_home.win=C\:\\Program Files\\Java\\jdk-11
framework.rundeck.url=http\://localhost\:4440
rundeck.server.logDir=C\:/projetos/rundeck/server/logs
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
framework.project.description=
jetty.git.hash=27bde00a0b95a1d5bbee0eae7984f891d2d0f8c9
java.vendor.url.bug=https\://bugreport.java.com/bugreport/
framework.logs.dir.win=C\:\\projetos\\rundeck\\var\\logs
framework.crypto.keystore.password=
user.dir=C\:\\projetos\\rundeck
os.arch=amd64
rundeck.server.uuid=e4781303-db15-4038-a190-51e5a55e18a1
jndi.connectionUrl=ldap\://localhost\:3890/
grails.env.standalone=true
framework.email.tolist=root
framework.crypto.keystore.filename=
java.vm.info=mixed mode
java.vm.version=11.0.24+7-LTS-271
framework.etc.dir=C\:/projetos/rundeck/etc
framework.var.dir.win=C\:\\projetos\\rundeck\\var
framework.projects.dir=C\:/projetos/rundeck/projects
java.class.version=55.0
